# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8d58cace4fd34b8612c23ee5ed4278fa67a6f0c83ac3ec7c21bb077ce102dbee1b492de0fbf00a9cc081adbc902b3615bcb9695bddf530ef36c3cb1a852a14b

test:
  secret_key_base: bdd2698f2b700a46ab25e7b54d1d1de78c0f4cb6812c4dde66b46a78b90efdc18713ac6aa5efbd6ac0fc3b7a2f77df218c3a4be9ddbd46e1f103211d18451f8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
